# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from luminosity_drone/Biolocation.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Biolocation(genpy.Message):
  _md5sum = "101e3ee1346387705dd3316e6b7bd9bd"
  _type = "luminosity_drone/Biolocation"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string organism_type
float64 whycon_x
float64 whycon_y
float64 whycon_z
"""
  __slots__ = ['organism_type','whycon_x','whycon_y','whycon_z']
  _slot_types = ['string','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       organism_type,whycon_x,whycon_y,whycon_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Biolocation, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.organism_type is None:
        self.organism_type = ''
      if self.whycon_x is None:
        self.whycon_x = 0.
      if self.whycon_y is None:
        self.whycon_y = 0.
      if self.whycon_z is None:
        self.whycon_z = 0.
    else:
      self.organism_type = ''
      self.whycon_x = 0.
      self.whycon_y = 0.
      self.whycon_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.organism_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.whycon_x, _x.whycon_y, _x.whycon_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.organism_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.organism_type = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.whycon_x, _x.whycon_y, _x.whycon_z,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.organism_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.whycon_x, _x.whycon_y, _x.whycon_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.organism_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.organism_type = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.whycon_x, _x.whycon_y, _x.whycon_z,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
